version: '3'
services:
  nginx-proxy:
    container_name: nginx-porxy
    image: nginx
    ports:
      - "8081:80"
    volumes:
      # 將 nginx 設定檔掛出來，提供設定 proxy
      - ./nginx.conf:/etc/nginx/nginx.conf