version: '3.1'
services:
  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    volumes:
      - ./verdaccio/storage:/verdaccio/storage
      # - ./htpasswd:/verdaccio/storage/htpasswd
    ports:
      - 4873:4873